services:
  - type: web
    name: myne-paystack-proxy
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PAYSTACK_SECRET_KEY
        sync: false   # you will set it manually in Render dashboard
      - key: POCKETBASE_URL
        value: https://myne-pos.fly.dev   # your Fly.io PocketBase URL
      - key: PB_ADMIN_EMAIL
        sync: false
      - key: PB_ADMIN_PASSWORD
        sync: false
